name: Build images

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install parted wget dosfstools zip

      # Build Images
      # Note: Uploading zip file artifact will be double zip. Do not delete .img file
      # See https://github.com/actions/upload-artifact#zipped-artifact-downloads

      
      
      - name: Build Raspberry Pi 3 AArch64 Image
        run: |
          sudo bash create-image aarch64 2G
          sudo cp rpi-aarch64-archlinux.img rpi-3-aarch64-archlinux.img
          zip -v rpi-3-aarch64-archlinux.img.zip rpi-3-aarch64-archlinux.img



      # Upload artifacts

      

      - name: Upload Raspberry Pi 3 AArch64 Image artifact
        uses: actions/upload-artifact@v2
        with:
          name: rpi-3-aarch64-archlinux.img
          path: rpi-3-aarch64-archlinux.img

      

      # Upload to release
      - name: Upload images to release
        uses: softprops/action-gh-release@v0.1.6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            rpi-3-aarch64-archlinux.img.zip
            
        env:
          GITHUB_TOKEN: ${{ github.token }}
